/**************************************************************************
 * 	Purpose: Contant Values that the org uses
 * 	Author:	 Steven Zhao
 * 	Created Date:	
 * 	Last Modifyied Author:
 *  Last Modifyied Date:
 * 	Description:	
 *************************************************************************/ 
public class OrgContants
{
//	public static Final list<schema.PicklistEntry>  PICKLISTVALUE_GENDER = Contact.Gender__c.getDescribe().getpicklistValues();

}